version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: booster-hub-db-img
    container_name: booster-hub-db-ctn
    networks:
      - booster-hub-network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: booster-hub-backend-img
    container_name: booster-hub-backend-ctn
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - booster-hub-network
    depends_on:
      database:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://test_user:password@database:5432/app_db

networks:
  booster-hub-network:
    driver: bridge
