version: '3.8'

services:
  postgres-db:
    build:
      context: .  
      dockerfile: Dockerfile
    image: postgres-db-img
    container_name: postgres-db-ctn
    ports:
      - "5432:5432"   
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:

